<div class="needs-validation main">
    <nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
        <div class="navbar-multiline mr-auto">
            <span class="navbar-brand" href="#0">Profile Account Editor</span>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminProfile') ?>">Profile</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><?= $subtitle ?></li>
                </ol>
            </nav>
        </div>
        <a href="<?= $this->router->to('adminProfileGalleryEdit', ['profile'=>$profile->id,'id'=>0]) ?>" class="btn btn-primary">Create New</a>
    </nav>

    <div class="container p-3">
        <div class="row mb-3">
            <div class="col-md-3">
                <div class="card mb-3">
                    <form method="GET" class="card-body">
                        <h5 class="card-title">Search</h5>
                        <?= $form->field('q') ?>
                        <div class="text-right">
                            <button class="btn btn-primary">Find</button>
                        </div>
                    </form>
                </div>

                <?= $this->partial('profile/editor-sidebar') ?>
            </div>
            <div class="col-md-9">
                <?php if($galleries): ?>
                <?php $csrf = $form->csrfToken(); ?>
                <ul class="list-group list-group-flush card mb-3">
                    <?php foreach($galleries as $gallery): ?>
                        <li class="list-group-item">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">
                                    <?= $gallery->title->safe ?>
                                </h5>
                                <div>
                                    <div class="btn-group btn-group-sm" role="group" aria-label="Action">
                                        <a href="<?= $this->router->to('adminProfileGalleryEdit', ['profile'=>$profile->id,'id'=>$gallery->id->value]) ?>" class="btn btn-secondary" title="Edit">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <?php if(isset($gallery->page)): ?>
                                            <a href="<?= $gallery->page ?>" class="btn btn-secondary" title="View Page" target="_blank">
                                                <i class="fas fa-external-link-square-alt"></i>
                                            </a>
                                        <?php endif; ?>
                                        <div class="btn-group btn-group-sm" role="group">
                                            <button id="profile-gallery-action-<?= $gallery->id ?>" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                                            <div class="dropdown-menu" aria-labelledby="profile-gallery-action-<?= $gallery->id ?>">
                                                <a class="dropdown-item"
                                                    data-toggle="confirm"
                                                    data-text="Are you sure want to remove this item?"
                                                    data-btn-type="danger"
                                                    href="<?= $this->router->to('adminProfileGalleryRemove', ['profile'=>$profile->id,'id'=>$gallery->id], ['noob'=>$csrf]) ?>">Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <small>
                                <span title="Created">
                                    <i class="far fa-calendar-plus"></i>
                                    <?= $gallery->created->format('M d, Y H:i') ?>
                                </span>
                                <?php if($gallery->user): ?>
                                    &middot;
                                    <span title="Creator">
                                        <i class="fas fa-user"></i>
                                        <?= $gallery->user->fullname->safe ?>
                                    </span>
                                <?php endif; ?>
                            </small>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <?php endif; ?>
                <?php if($pages): ?>
                    <?= $this->partial('shared/pagination', ['pages'=>$pages, 'align'=>'right']); ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>